In [1]:
import numpy as np

np.__version__

'1.24.3'

In [2]:
arr1 = np.arange(10)

In [3]:
arr1.shape

(10,)

In [4]:
print(arr1)
print(arr1[6])
print(arr1[2:8])
print(arr1[-6:-1-1])

[0 1 2 3 4 5 6 7 8 9]
6
[2 3 4 5 6 7]
[4 5 6 7]


In [5]:
indice = [x for x in range(5)]

In [6]:
print(arr1[indice])

[0 1 2 3 4]


In [7]:
print(arr1[(arr1 % 2 == 0)])

[0 2 4 6 8]


In [8]:
try:
    arr1[0] = 'Novo elemento de tipo diferente'
except:
    print('Operação inválida. \nNumPy não suporta tipos diferentes.')

Operação inválida. 
NumPy não suporta tipos diferentes.


In [9]:
arr2 = np.array([1, 2, 3, 4, 5])
print(arr2.cumsum())
print(arr2.cumprod())

[ 1  3  6 10 15]
[  1   2   6  24 120]


In [10]:
arr3 = np.arange(0, 50, 5)
print(np.shape(arr3))
print(arr3.dtype)

(10,)
int32


In [11]:
arr4 = np.zeros(5)
arr5 = np.eye(3)
arr6 = np.diag(np.array([1, 2, 3, 4]))

In [12]:
print(arr4)

[0. 0. 0. 0. 0.]


In [13]:
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
